### PR TITLE
Errors

### LINKED ISSUE #12: Add URI to the Error class
We receive about 3-100 errors from Shippo every day; it would be useful if the error objects contained information about which URI was failing, so we could use this information to escalate to Shippo. 

I tried adding this, but got stopped because I wasn't sure about the type of the `req` variable in makeRequest(), and/or how to get the URI back out in the `_responseHandler`.

### LINKED ISSUE #14: Expose error constructors
It would be great to have the following Error constructors available on the exported Shippo object. The only way to detect a specific type of error currently is to compare the `type` property against a string, which isn't ideal.

```
ShippoNotFoundError
ShippoInvalidRequestError
ShippoAPIError
ShippoAuthenticationError
ShippoConnectionError
```

### PR DESCRIPTION
**Pull request by epistemancer**
* expose error classes in Shippo instances
* populate more attributes on Error object
* flatten promise chains in examples (to more clearly demonstrate how errors can be caught at each step)

resolves #12, resolves #14

### CODE REVIEW

File: lib/Resource.js [hunk 1]
```diff
@@ -120,23 +120,24 @@ Resource.prototype = {
                     );
                 }
 
+                var errData = {
+                    code: res.statusCode,
```
Comment (malcolmrebughini) [inline lib/Resource.js:124]: Can we call this `statusCode`? might be good to leave `code` for our own internal error codes.
